INSERT INTO comments (user_id, resource_id, comments) VALUES (1, 2, "wow")
INSERT INTO comments (user_id, resource_id, comments) VALUES (2, 2, "amazing")
INSERT INTO comments (user_id, resource_id, comments) VALUES (3, 3, "")
INSERT INTO comments (user_id, resource_id, comments) VALUES (4, 4, "cant wait for this game release")
INSERT INTO comments (user_id, resource_id, comments) VALUES (5, 5, "I love this song")
INSERT INTO comments (user_id, resource_id, comments) VALUES (6, 6, "")
INSERT INTO comments (user_id, resource_id, comments) VALUES (7, 7, "I've been looking for a new routine... this is perfect")
INSERT INTO comments (user_id, resource_id, comments) VALUES (8, 8, "adding this location to my bucket list")
INSERT INTO comments (user_id, resource_id, comments) VALUES (9, 9, "delicious! I will be trying this recipe later today")
INSERT INTO comments (user_id, resource_id, comments) VALUES (10, 10, "This is my favourite makeup tutorial!!")
