INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (1, 1, 200)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (2, 2, 1400)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (3, 3, 500)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (4, 4, 1500)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (5, 5, 2000)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (6, 6, 100)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (7, 7, 400)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (8, 8, 400)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (9, 9, 100)
INSERT INTO resource_likes (user_id, resource_id, likes) VALUES (10, 10, 1200)

