INSERT INTO resources (id, title, description, topic, user_id) VALUES (1, "", "", "sport", 1)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (2, "", "", "art", 2)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (3, "", "", "tech", 3)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (4, "", "", "gaming", 4)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (5, "", "", "music", 5)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (6,"", "", "education", 6)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (7,"", "", "fitness", 7)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (8,"", "", "travel", 8)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (9,"", "", "cooking", 9)
INSERT INTO resources (id, title, description, topic, user_id) VALUES (10,"", "", "beauty", 10)
